#!/bin/sh

# Filename of the java executable.
JAVA_EXEC=java

# Get the path to the java executable.
if [ -x "jre/linux/bin/$JAVA_EXEC" ]; then
  echo "Found JRE at the current folder:"
  JAVA_DIR=jre/linux/bin/$JAVA_EXEC
elif [ -x "../jre/linux/bin/$JAVA_EXEC" ]; then
  echo "Found JRE one folder up:"
  JAVA_DIR=../jre/linux/bin/$JAVA_EXEC
elif [ -x "../../jre/linux/bin/$JAVA_EXEC" ]; then
  echo "Found JRE two folders up:"
  JAVA_DIR=../../jre/linux/bin/$JAVA_EXEC
elif [ -x "../../../jre/linux/bin/$JAVA_EXEC" ]; then
  echo "Found JRE three folders up:"
  JAVA_DIR=../../../jre/linux/bin/$JAVA_EXEC
elif [ -x "../../../../jre/linux/bin/$JAVA_EXEC" ]; then
  echo "Found JRE four folders up:"
  JAVA_DIR=../../../../jre/linux/bin/$JAVA_EXEC  
else
  echo "Using java from path:"
  JAVA_DIR=$JAVA_EXEC
fi  
  
echo $JAVA_DIR

echo $@
  
# Run command.
$JAVA_DIR ${build.tmp.jvmArgs} -jar "${build.tmp.launcherJarPath}" -m ${build.tmp.mainClass} -f ${build.tmp.launcherProperties} -e ${build.tmp.cmdLineArgs} $@
